import json
import os

# Even more content
new_black_cards = [
    {"text": "Co jest moją największą wadą genetyczną?", "pick": 1},
    {"text": "W 2024 roku Polska ogłosi wojnę z _____.", "pick": 1},
    {"text": "Co sprawia, że płaczę podczas orgazmu?", "pick": 1},
    {"text": "Jaki jest prawdziwy powód, dla którego kosmici nas nie odwiedzają?", "pick": 1},
    {"text": "Co znalazłem w pieluszce mojego dziecka?", "pick": 1},
    {"text": "Zanim umrę, chcę spróbować _____.", "pick": 1},
    {"text": "Co jest głównym składnikiem parówek z Biedronki?", "pick": 1},
    {"text": "Mój nowy start-up będzie polegał na sprzedawaniu _____.", "pick": 1},
    {"text": "Co jest jedyną rzeczą, która trzyma mnie przy życiu?", "pick": 1},
    {"text": "Wpiekło jest specjalne miejsce dla ludzi, którzy lubią _____.", "pick": 1},
    {"text": "Co powiedział lekarz po moim badaniu prostaty?", "pick": 1},
    {"text": "Co jest najdziwniejszą rzeczą, jaką można kupić w sex shopie?", "pick": 1},
    {"text": "Jaki jest tytuł mojego sekstaśmy?", "pick": 1},
    {"text": "Co jest najgorszym sposobem na zerwanie z dziewczyną?", "pick": 1},
    {"text": "Co bym zrobił, gdybym był Bogiem przez jeden dzień?", "pick": 1},
    {"text": "Co jest przyczyną smogu w Krakowie?", "pick": 1},
    {"text": "Co ukrywa Watykan?", "pick": 1},
    {"text": "Jaki jest sekretny składnik kremówek papieskich?", "pick": 1},
    {"text": "Co jest jedyną rzeczą gorszą od PiS-u?", "pick": 1},
    {"text": "Co jest jedyną rzeczą gorszą od PO?", "pick": 1},
    {"text": "Co bym zrobił z ciałem Lenina?", "pick": 1},
    {"text": "Co jest moją ulubioną pozycją seksualną?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można usłyszeć w konfesjonale?", "pick": 1},
    {"text": "Co jest powodem, dla którego nie mam przyjaciół?", "pick": 1},
    {"text": "Co jest moją największą fantazją seksualną?", "pick": 1},
    {"text": "Co jest najgorszym sposobem na śmierć?", "pick": 1},
    {"text": "Co jest najlepszym sposobem na samobójstwo?", "pick": 1},
    {"text": "Co jest moją ulubioną używką?", "pick": 1},
    {"text": "Co jest najgorszym nałogiem?", "pick": 1},
    {"text": "Co jest moją największą tajemnicą?", "pick": 1},
    {"text": "Co bym zrobił, gdybym wygrał w totka?", "pick": 1},
    {"text": "Co jest najgorszym prezentem ślubnym?", "pick": 1},
    {"text": "Co jest najgorszym imieniem dla dziecka?", "pick": 1},
    {"text": "Co jest najgorszą pracą na świecie?", "pick": 1},
    {"text": "Co jest najgorszym kierunkiem studiów?", "pick": 1},
    {"text": "Co jest najgorszym jedzeniem na świecie?", "pick": 1},
    {"text": "Co jest najgorszym filmem wszechczasów?", "pick": 1},
    {"text": "Co jest najgorszą piosenką disco polo?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą w Polsce?", "pick": 1},
    {"text": "Co jest najlepszą rzeczą w Polsce?", "pick": 1},
    {"text": "Co jest moją ulubioną teorią spiskową?", "pick": 1},
    {"text": "Co jest prawdą o Smoleńsku?", "pick": 1},
    {"text": "Co jest prawdą o lądowaniu na Księżycu?", "pick": 1},
    {"text": "Co jest prawdą o zamachu na WTC?", "pick": 1},
    {"text": "Co jest prawdą o szczepionkach?", "pick": 1},
    {"text": "Co jest prawdą o 5G?", "pick": 1},
    {"text": "Co jest prawdą o UFO?", "pick": 1},
    {"text": "Co jest prawdą o Ziemi?", "pick": 1},
    {"text": "Co jest prawdą o Bogu?", "pick": 1},
    {"text": "Co jest prawdą o Szatanie?", "pick": 1}
]

new_white_cards = [
    "Obciąganie bezdomnemu.",
    "Wylizywanie rowa.",
    "Złoty deszcz.",
    "Brązowy deszcz.",
    "Seks z karłem.",
    "Seks z inwalidą.",
    "Seks z downem.",
    "Seks z trupem babci.",
    "Gwałt na randce.",
    "Pigułka 'dzień po' jako cukierek.",
    "Wieszak do ubrań.",
    "Skrobanka domowym sposobem.",
    "Poronienie w toalecie publicznej.",
    "Martwy noworodek.",
    "Płód w słoiku.",
    "Handel organami.",
    "Wycinanie nerki w wannie.",
    "Kradzież tożsamości.",
    "Wyłudzenie metodą 'na wnuczka'.",
    "Kradzież katalizatora.",
    "Jebanie policji.",
    "Chwdp.",
    "Hwdp.",
    "Acab.",
    "Rzucanie kamieniami w policję.",
    "Palenie opon.",
    "Blokada rolnicza.",
    "Rozrzucanie gnoju pod sejmem.",
    "Wnoszenie broni do szkoły.",
    "Strzelanina w szkole.",
    "Masakra w Columbine.",
    "Anders Breivik.",
    "Trynkiewicz.",
    "Kajetan P.",
    "Wampir z Bytowa.",
    "Skorpion.",
    "Bestia z Wadowic.",
    "Jan Paweł 2.",
    "Karol Wojtyła.",
    "Papież Polak.",
    "Papież Franciszek.",
    "Papież Benedykt.",
    "Dziwisz.",
    "Głódź.",
    "Jędraszewski.",
    "Michalik.",
    "Rydzyk.",
    "Radio Maryja.",
    "Telewizja Trwam.",
    "Nasz Dziennik.",
    "Gazeta Polska.",
    "Do Rzeczy.",
    "Sieci.",
    "Wiadomości TVP.",
    "Panorama.",
    "Teleexpress.",
    "Fakty TVN.",
    "Wydarzenia Polsat.",
    "Kropka nad i.",
    "Szkło Kontaktowe.",
    "Sprawa dla reportera.",
    "Jaworowicz.",
    "Sznuk.",
    "Jeden z dziesięciu.",
    "Familiada.",
    "Karol Strasburger.",
    "Suchar Strasburgera.",
    "Koło Fortuny.",
    "Jaka to melodia.",
    "Robert Janowski.",
    "Rafał Brzozowski.",
    "Norbi.",
    "Zenek Martyniuk.",
    "Akcent.",
    "Boys.",
    "Marcin Miller.",
    "Sławomir.",
    "Kajra.",
    "Czadoman.",
    "Weekend.",
    "Ona tańczy dla mnie.",
    "Przez twe oczy zielone.",
    "Miłość w Zakopanem.",
    "Ruda tańczy jak szalona.",
    "Jesteś szalona.",
    "Mydelniczka.",
    "Majteczki w kropeczki.",
    "Biały miś.",
    "Czerwone gitary.",
    "Maryla Rodowicz.",
    "Krzysztof Krawczyk.",
    "Zbigniew Wodecki.",
    "Czesław Niemen.",
    "Marek Grechuta.",
    "Dżem.",
    "Ryszard Riedel.",
    "Whisky moja żono.",
    "Wehikuł czasu.",
    "List do M.",
    "Autobiografia.",
    "Perfect.",
    "Lady Pank.",
    "Mniej niż zero.",
    "Kult.",
    "Kazik.",
    "Tata Kazika.",
    "Polska.",
    "Arahja.",
    "Baranek.",
    "Celina.",
    "12 groszy.",
    "Gdy nie ma dzieci.",
    "Mieszkam w Polsce.",
    "Chłopaki nie płaczą.",
    "Poranek kojota.",
    "Kiler.",
    "Psy.",
    "Psy 2.",
    "Dzień świra.",
    "Wszyscy jesteśmy Chrystusami.",
    "Nic śmiesznego.",
    "Alternatywy 4.",
    "Zmiennicy.",
    "Miś.",
    "Rejs.",
    "Seksmisja.",
    "Vabank.",
    "Kogel-mogel.",
    "Sami swoi.",
    "Czterej pancerni i pies.",
    "Stawka większa niż życie.",
    "Janosik.",
    "Bolek i Lolek.",
    "Reksio.",
    "Koziołek Matołek.",
    "Miś Uszatek.",
    "Pszczółka Maja.",
    "Smerfy.",
    "Gumisie.",
    "Muminki.",
    "Buka.",
    "Hatifnatowie.",
    "Włóczykij.",
    "Mała Mi.",
    "Tatuś Muminka.",
    "Mamusia Muminka.",
    "Paszczak.",
    "Ryjek.",
    "Migotka.",
    "Topielica.",
    "Rusałka.",
    "Południca.",
    "Strzyga.",
    "Utopiec.",
    "Wodnik.",
    "Leszy.",
    "Baba Jaga.",
    "Smok Wawelski.",
    "Lajkonik.",
    "Syrenka Warszawska.",
    "Koziołki Poznańskie.",
    "Krasnale Wrocławskie.",
    "Piernik Toruński.",
    "Oscypek.",
    "Ciupaga.",
    "Kierpce.",
    "Górale.",
    "Ślązacy.",
    "Kaszubi.",
    "Warszawiacy.",
    "Słoiki.",
    "Krakusy.",
    "Centusie.",
    "Pyry.",
    "Pyrlandia.",
    "Białystok.",
    "Podlasie.",
    "Kononowicz.",
    "Major Suchodolski.",
    "Szkolna 17.",
    "Mleczny Człowiek.",
    "Choroszcz.",
    "Szpital psychiatryczny.",
    "Psychiatryk.",
    "Dom wariatów.",
    "Żółte papiery.",
    "Ubezwłasnowolnienie.",
    "Kurator.",
    "Dozór policyjny.",
    "Bransoletka.",
    "Areszt domowy.",
    "Wyrok w zawieszeniu.",
    "Recydywa.",
    "Grypsera.",
    "Cwel.",
    "Pedał.",
    "Gej.",
    "Lesbijka.",
    "Trans.",
    "Bi.",
    "Queer.",
    "Non-binary.",
    "Helikopter bojowy.",
    "Zaimki.",
    "Poprawność polityczna.",
    "Cancel culture.",
    "Woke.",
    "Lewactwo.",
    "Prawactwo.",
    "Faszyzm.",
    "Komunizm.",
    "Socjalizm.",
    "Kapitalizm.",
    "Liberalizm.",
    "Konserwatyzm.",
    "Nacjonalizm.",
    "Patriotyzm.",
    "Szowinizm.",
    "Feminizm.",
    "Maskulinizm.",
    "Seksizm.",
    "Rasizm.",
    "Antysemityzm.",
    "Islamofobia.",
    "Homofobia.",
    "Transfobia.",
    "Ksenofobia."
]

card_file = 'cards.json'

try:
    with open(card_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
except FileNotFoundError:
    data = {"blackCards": [], "whiteCards": []}

# Simple deduplication based on text
existing_black = {c['text'] for c in data['blackCards']}
existing_white = set(data['whiteCards'])

added_black = 0
added_white = 0

for c in new_black_cards:
    if c['text'] not in existing_black:
        data['blackCards'].append(c)
        added_black += 1

for c in new_white_cards:
    if c not in existing_white:
        data['whiteCards'].append(c)
        added_white += 1

with open(card_file, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {added_black} more black cards and {added_white} more white cards.")
