import json
import os

# Final batch of content
new_black_cards = [
    {"text": "Co jest moją supermocą po alkoholu?", "pick": 1},
    {"text": "W nowym programie 'Rolnik szuka żony', rolnik szuka _____.", "pick": 1},
    {"text": "Co znalazłem w kanapce z Subwaya?", "pick": 1},
    {"text": "Dlaczego zostałem wyrzucony z przedszkola?", "pick": 1},
    {"text": "Co jest najlepszym sposobem na podryw na tinderze?", "pick": 1},
    {"text": "Co jest moją ulubioną zabawką erotyczną?", "pick": 1},
    {"text": "Co jest przyczyną moich problemów finansowych?", "pick": 1},
    {"text": "Co jest jedyną rzeczą, której brakuje w moim życiu seksualnym?", "pick": 1},
    {"text": "Co jest najgorszym miejscem na oświadczyny?", "pick": 1},
    {"text": "Co jest najgorszym tatuażem, jaki można sobie zrobić?", "pick": 1},
    {"text": "Co jest najgorszym prezentem na Dzień Matki?", "pick": 1},
    {"text": "Co jest najgorszym sposobem na spędzenie niedzieli?", "pick": 1},
    {"text": "Co jest najgorszym filmem porno, jaki widziałem?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można powiedzieć podczas orgazmu?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można znaleźć w internecie?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić w kościele?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić na pogrzebie?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić w pracy?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić w szkole?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić w szpitalu?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić w samolocie?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić w windzie?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić w toalecie publicznej?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić na randce?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić w łóżku?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić ze zwierzęciem?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z dzieckiem?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić ze zwłokami?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z jedzeniem?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z pieniędzmi?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z samochodem?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z telefonem?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z komputerem?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z telewizorem?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z meblami?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z ubraniami?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z butami?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z książką?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z gazetą?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z listem?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z paczką?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z prezentem?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z tortem?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z pizzą?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z kebabem?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z piwem?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z wódką?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z winem?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z wodą?", "pick": 1},
    {"text": "Co jest najgorszą rzeczą, jaką można zrobić z ogniem?", "pick": 1}
]

new_white_cards = [
    "Seks z nieznajomym.",
    "Seks z przyjacielem.",
    "Seks z wrogiem.",
    "Seks z szefem.",
    "Seks z nauczycielem.",
    "Seks z uczniem.",
    "Seks z lekarzem.",
    "Seks z pacjentem.",
    "Seks z prawnikiem.",
    "Seks z klientem.",
    "Seks z policjantem.",
    "Seks z więźniem.",
    "Seks z księdzem.",
    "Seks z zakonnicą.",
    "Seks z ministrantem.",
    "Seks z celebrytą.",
    "Seks z politykiem.",
    "Seks z kosmitą.",
    "Seks z robotem.",
    "Seks z duchem.",
    "Seks z wampirem.",
    "Seks z wilkołakiem.",
    "Seks z zombie.",
    "Seks z potworem.",
    "Seks z diabłem.",
    "Seks z aniołem.",
    "Seks z Bogiem.",
    "Masturbacja przed lustrem.",
    "Masturbacja przed kamerą.",
    "Masturbacja w pracy.",
    "Masturbacja w szkole.",
    "Masturbacja w kościele.",
    "Masturbacja w autobusie.",
    "Masturbacja w pociągu.",
    "Masturbacja w samolocie.",
    "Masturbacja w kinie.",
    "Masturbacja w teatrze.",
    "Masturbacja w muzeum.",
    "Masturbacja w parku.",
    "Masturbacja na plaży.",
    "Masturbacja na basenie.",
    "Masturbacja na siłowni.",
    "Masturbacja w saunie.",
    "Masturbacja w windzie.",
    "Masturbacja na schodach.",
    "Masturbacja na dachu.",
    "Masturbacja w piwnicy.",
    "Masturbacja na strychu.",
    "Masturbacja w lesie.",
    "Masturbacja na łące.",
    "Oglądanie porno z rodzicami.",
    "Oglądanie porno z dziećmi.",
    "Oglądanie porno z dziadkami.",
    "Oglądanie porno z sąsiadami.",
    "Oglądanie porno z szefem.",
    "Oglądanie porno z księdzem.",
    "Kręcenie porno w domu.",
    "Kręcenie porno w pracy.",
    "Kręcenie porno w szkole.",
    "Kręcenie porno w kościele.",
    "Udział w orgii.",
    "Udział w gangbangu.",
    "Udział w bukkake.",
    "Udział w gloryhole.",
    "Sprzedawanie nudesów.",
    "Kupowanie nudesów.",
    "Wysyłanie dickpicków.",
    "Dostawanie dickpicków.",
    "Sexting z mamą.",
    "Sexting z tatą.",
    "Sexting z siostrą.",
    "Sexting z bratem.",
    "Sexting z babcią.",
    "Sexting z dziadkiem.",
    "Zdrada męża.",
    "Zdrada żony.",
    "Zdrada chłopaka.",
    "Zdrada dziewczyny.",
    "Rozwód z orzekaniem o winie.",
    "Alimenty na cudze dziecko.",
    "Test na ojcostwo w TV.",
    "Aborcja na życzenie.",
    "Aborcja farmakologiczna.",
    "Tabletka dzień po.",
    "Prezerwatywa z Biedronki.",
    "Pęknięta gumka.",
    "Ciąża z wpadki.",
    "In vitro.",
    "Adopcja dziecka z Afryki.",
    "Sprzedaż dziecka na Allegro.",
    "Oddanie dziecka do okna życia.",
    "Porzucenie dziecka w lesie.",
    "Utopienie dziecka w beczce.",
    "Zamrażarka z noworodkami.",
    "Bicie żony kablem.",
    "Bicie męża patelnią.",
    "Bicie dzieci pasem.",
    "Znęcanie się nad zwierzętami.",
    "Podpalenie kota.",
    "Utopienie psa.",
    "Otrucie gołębi.",
    "Strzelanie do dzików.",
    "Polowanie na lisy.",
    "Futro z norek.",
    "Testowanie kosmetyków na zwierzętach.",
    "Cyrk ze zwierzętami.",
    "Zoo.",
    "Rzeźnia.",
    "Ubojnia rytualna.",
    "Kebab z psa.",
    "Sajgonki z kota.",
    "Nietoperz z Wuhan.",
    "Zupa z płetwy rekina.",
    "Mózg małpy.",
    "Jądra byka.",
    "Krew węża.",
    "Larwy jedwabnika.",
    "Szarańcza w czekoladzie.",
    "Karaluchy w cukrze.",
    "Pająki w galarecie.",
    "Dżdżownice w sosie.",
    "Ślimaki w czosnku.",
    "Żabie udka.",
    "Ośmiorniczki.",
    "Kawior.",
    "Trufle.",
    "Szampan z truskawkami.",
    "Wino za 5 zł.",
    "Piwo z puszki.",
    "Wódka z mety.",
    "Denaturat przez chleb.",
    "Borygo z colą.",
    "Rozpuszczalnik nitro.",
    "Klej butapren.",
    "Benzyna ołowiowa.",
    "Gaz do zapalniczek.",
    "Odświeżacz powietrza.",
    "Lakier do włosów.",
    "Farba olejna.",
    "Zmywacz do paznokci.",
    "Aceton.",
    "Kwas siarkowy.",
    "Arszenik.",
    "Cyjanek.",
    "Strychnina.",
    "Trutka na szczury.",
    " muchozol.",
    "Domestos.",
    "Kret do rur.",
    "Wybielacz.",
    "Proszek do prania.",
    "Tabletki do zmywarki.",
    "Kapsułki do prania.",
    "Płyn do naczyń.",
    "Płyn do szyb.",
    "Płyn do podłóg.",
    "Pasta do butów.",
    "Smar do łańcucha.",
    "Olej silnikowy.",
    "Płyn hamulcowy.",
    "Płyn chłodniczy.",
    "Elektrolit z akumulatora."
]

card_file = 'cards.json'

try:
    with open(card_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
except FileNotFoundError:
    data = {"blackCards": [], "whiteCards": []}

# Simple deduplication based on text
existing_black = {c['text'] for c in data['blackCards']}
existing_white = set(data['whiteCards'])

added_black = 0
added_white = 0

for c in new_black_cards:
    if c['text'] not in existing_black:
        data['blackCards'].append(c)
        added_black += 1

for c in new_white_cards:
    if c not in existing_white:
        data['whiteCards'].append(c)
        added_white += 1

with open(card_file, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {added_black} final black cards and {added_white} final white cards.")
